version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - errorlint
    - misspell
    - revive
    - unconvert

formatters:
  enable:
    - gofmt
    - goimports
